# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d7fb587bea7bca2ee6bee7a79b3a98e67d53e3f863490271b9bab0ff33d7cc85526dc52a63d3f2434e06241a4be9297d236910f71cf8e5d1703bb1083254c9a

test:
  secret_key_base: 1be763f012cb1fc5ce20327a60355f36f42689fe08749ef6ccfc03e151a2ef7a9d9fb056f69143642d9a1f75ebc5598acab15513381df67e1a1088fa7a9de469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
